sudo: false

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

install:
  - corepack enable
  - pnpm install --frozen-lockfile

cache:
  pnpm: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - pnpm lint
  - pnpm test
  - pnpm build
